Algoritmo "EX1_LISTA1"

Var
   p1,p2,p3: real
   m:real

Inicio
      escreval("Chegando no primeiro posto, qual foi o valor da gasolina?")
      leia(p1)
      escreval("Chegando no segundo posto, qual foi o valor da gasolina?")
      leia(p2)
      escreval("Chegando no terceiro posto, qual foi o valor da gasolina?")
      leia(p3)
      
      m<- (p1+p2+p3)/3
      
      escreval("Com base nos valores dados por você, o valor médio da gasolina nesses três postos de Salvador é ",m)
      
Fimalgoritmo